#!/bin/bash
set -e

mlgpus() {
    A=(/proc/driver/nvidia/gpus/*)
    if [ -e "${A[0]}" ]
    then echo "${#A[*]}"
    else echo "0"
    fi
}
export MLGPUS=${MLGPUS:-$(mlgpus)}
export DATA=${DATA:-$(readlink -f data)} # user can symlink a custom path
export DATA=${DATA:-/data}

ARGS=(
    --mount=type=bind,source="$PWD",destination=/src
    --mount=type=bind,source="$DATA",destination=/data
    --env=TRANSFORMERS_CACHE=/data/cache/huggingface/transformers
    --env=HF_DATASETS_CACHE=/data/cache/huggingface/datasets
    --env=LANG
    --workdir=/src
)
if [ "$MLGPUS" -gt 0 ]
then
    ARGS=("${ARGS[@]}" --runtime=nvidia)
fi

[ -t 0 ] && ARGS=(-ti "${ARGS[@]}")

case "$1" in
    --build)
        docker build docker --tag rnd-html
        shift
        ;;
esac

docker run --rm "${ARGS[@]}" rnd-html "$@"
